# This file must be in sync with .testcoverage.yaml that can be used locally.
coverage:
  status:
    project:
      default:
        target: 86%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
ignore:
  - "cmd"
  - "examples"
  - "**/*.pb.go"
  - "**/zz_generated.*.go"
  - "tests/internal/envtest.go"
  - "tests/internal/e2elib/**/*"
  - "tests/internal/testenvironment/**/*"
  - "tests/internal/testopeninference/openai_proxy.go"
  - "tests/internal/testmcp/**/*"
  - "internal/testing/**/*"
  - "internal/controller/controller.go"
