// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AIGatewayRouteLister helps list AIGatewayRoutes.
// All objects returned here must be treated as read-only.
type AIGatewayRouteLister interface {
	// List lists all AIGatewayRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.AIGatewayRoute, err error)
	// AIGatewayRoutes returns an object that can list and get AIGatewayRoutes.
	AIGatewayRoutes(namespace string) AIGatewayRouteNamespaceLister
	AIGatewayRouteListerExpansion
}

// aIGatewayRouteLister implements the AIGatewayRouteLister interface.
type aIGatewayRouteLister struct {
	listers.ResourceIndexer[*apiv1alpha1.AIGatewayRoute]
}

// NewAIGatewayRouteLister returns a new AIGatewayRouteLister.
func NewAIGatewayRouteLister(indexer cache.Indexer) AIGatewayRouteLister {
	return &aIGatewayRouteLister{listers.New[*apiv1alpha1.AIGatewayRoute](indexer, apiv1alpha1.Resource("aigatewayroute"))}
}

// AIGatewayRoutes returns an object that can list and get AIGatewayRoutes.
func (s *aIGatewayRouteLister) AIGatewayRoutes(namespace string) AIGatewayRouteNamespaceLister {
	return aIGatewayRouteNamespaceLister{listers.NewNamespaced[*apiv1alpha1.AIGatewayRoute](s.ResourceIndexer, namespace)}
}

// AIGatewayRouteNamespaceLister helps list and get AIGatewayRoutes.
// All objects returned here must be treated as read-only.
type AIGatewayRouteNamespaceLister interface {
	// List lists all AIGatewayRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.AIGatewayRoute, err error)
	// Get retrieves the AIGatewayRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.AIGatewayRoute, error)
	AIGatewayRouteNamespaceListerExpansion
}

// aIGatewayRouteNamespaceLister implements the AIGatewayRouteNamespaceLister
// interface.
type aIGatewayRouteNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.AIGatewayRoute]
}
