// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AIGatewayRouteListerExpansion allows custom methods to be added to
// AIGatewayRouteLister.
type AIGatewayRouteListerExpansion interface{}

// AIGatewayRouteNamespaceListerExpansion allows custom methods to be added to
// AIGatewayRouteNamespaceLister.
type AIGatewayRouteNamespaceListerExpansion interface{}

// AIServiceBackendListerExpansion allows custom methods to be added to
// AIServiceBackendLister.
type AIServiceBackendListerExpansion interface{}

// AIServiceBackendNamespaceListerExpansion allows custom methods to be added to
// AIServiceBackendNamespaceLister.
type AIServiceBackendNamespaceListerExpansion interface{}

// BackendSecurityPolicyListerExpansion allows custom methods to be added to
// BackendSecurityPolicyLister.
type BackendSecurityPolicyListerExpansion interface{}

// BackendSecurityPolicyNamespaceListerExpansion allows custom methods to be added to
// BackendSecurityPolicyNamespaceLister.
type BackendSecurityPolicyNamespaceListerExpansion interface{}

// MCPRouteListerExpansion allows custom methods to be added to
// MCPRouteLister.
type MCPRouteListerExpansion interface{}

// MCPRouteNamespaceListerExpansion allows custom methods to be added to
// MCPRouteNamespaceLister.
type MCPRouteNamespaceListerExpansion interface{}
