// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MCPRouteLister helps list MCPRoutes.
// All objects returned here must be treated as read-only.
type MCPRouteLister interface {
	// List lists all MCPRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.MCPRoute, err error)
	// MCPRoutes returns an object that can list and get MCPRoutes.
	MCPRoutes(namespace string) MCPRouteNamespaceLister
	MCPRouteListerExpansion
}

// mCPRouteLister implements the MCPRouteLister interface.
type mCPRouteLister struct {
	listers.ResourceIndexer[*apiv1alpha1.MCPRoute]
}

// NewMCPRouteLister returns a new MCPRouteLister.
func NewMCPRouteLister(indexer cache.Indexer) MCPRouteLister {
	return &mCPRouteLister{listers.New[*apiv1alpha1.MCPRoute](indexer, apiv1alpha1.Resource("mcproute"))}
}

// MCPRoutes returns an object that can list and get MCPRoutes.
func (s *mCPRouteLister) MCPRoutes(namespace string) MCPRouteNamespaceLister {
	return mCPRouteNamespaceLister{listers.NewNamespaced[*apiv1alpha1.MCPRoute](s.ResourceIndexer, namespace)}
}

// MCPRouteNamespaceLister helps list and get MCPRoutes.
// All objects returned here must be treated as read-only.
type MCPRouteNamespaceLister interface {
	// List lists all MCPRoutes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.MCPRoute, err error)
	// Get retrieves the MCPRoute from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.MCPRoute, error)
	MCPRouteNamespaceListerExpansion
}

// mCPRouteNamespaceLister implements the MCPRouteNamespaceLister
// interface.
type mCPRouteNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.MCPRoute]
}
