// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AIGatewayRoutesGetter has a method to return a AIGatewayRouteInterface.
// A group's client should implement this interface.
type AIGatewayRoutesGetter interface {
	AIGatewayRoutes(namespace string) AIGatewayRouteInterface
}

// AIGatewayRouteInterface has methods to work with AIGatewayRoute resources.
type AIGatewayRouteInterface interface {
	Create(ctx context.Context, aIGatewayRoute *apiv1alpha1.AIGatewayRoute, opts v1.CreateOptions) (*apiv1alpha1.AIGatewayRoute, error)
	Update(ctx context.Context, aIGatewayRoute *apiv1alpha1.AIGatewayRoute, opts v1.UpdateOptions) (*apiv1alpha1.AIGatewayRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aIGatewayRoute *apiv1alpha1.AIGatewayRoute, opts v1.UpdateOptions) (*apiv1alpha1.AIGatewayRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.AIGatewayRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.AIGatewayRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.AIGatewayRoute, err error)
	AIGatewayRouteExpansion
}

// aIGatewayRoutes implements AIGatewayRouteInterface
type aIGatewayRoutes struct {
	*gentype.ClientWithList[*apiv1alpha1.AIGatewayRoute, *apiv1alpha1.AIGatewayRouteList]
}

// newAIGatewayRoutes returns a AIGatewayRoutes
func newAIGatewayRoutes(c *AigatewayV1alpha1Client, namespace string) *aIGatewayRoutes {
	return &aIGatewayRoutes{
		gentype.NewClientWithList[*apiv1alpha1.AIGatewayRoute, *apiv1alpha1.AIGatewayRouteList](
			"aigatewayroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.AIGatewayRoute { return &apiv1alpha1.AIGatewayRoute{} },
			func() *apiv1alpha1.AIGatewayRouteList { return &apiv1alpha1.AIGatewayRouteList{} },
		),
	}
}
