// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BackendSecurityPoliciesGetter has a method to return a BackendSecurityPolicyInterface.
// A group's client should implement this interface.
type BackendSecurityPoliciesGetter interface {
	BackendSecurityPolicies(namespace string) BackendSecurityPolicyInterface
}

// BackendSecurityPolicyInterface has methods to work with BackendSecurityPolicy resources.
type BackendSecurityPolicyInterface interface {
	Create(ctx context.Context, backendSecurityPolicy *apiv1alpha1.BackendSecurityPolicy, opts v1.CreateOptions) (*apiv1alpha1.BackendSecurityPolicy, error)
	Update(ctx context.Context, backendSecurityPolicy *apiv1alpha1.BackendSecurityPolicy, opts v1.UpdateOptions) (*apiv1alpha1.BackendSecurityPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backendSecurityPolicy *apiv1alpha1.BackendSecurityPolicy, opts v1.UpdateOptions) (*apiv1alpha1.BackendSecurityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.BackendSecurityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.BackendSecurityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.BackendSecurityPolicy, err error)
	BackendSecurityPolicyExpansion
}

// backendSecurityPolicies implements BackendSecurityPolicyInterface
type backendSecurityPolicies struct {
	*gentype.ClientWithList[*apiv1alpha1.BackendSecurityPolicy, *apiv1alpha1.BackendSecurityPolicyList]
}

// newBackendSecurityPolicies returns a BackendSecurityPolicies
func newBackendSecurityPolicies(c *AigatewayV1alpha1Client, namespace string) *backendSecurityPolicies {
	return &backendSecurityPolicies{
		gentype.NewClientWithList[*apiv1alpha1.BackendSecurityPolicy, *apiv1alpha1.BackendSecurityPolicyList](
			"backendsecuritypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.BackendSecurityPolicy { return &apiv1alpha1.BackendSecurityPolicy{} },
			func() *apiv1alpha1.BackendSecurityPolicyList { return &apiv1alpha1.BackendSecurityPolicyList{} },
		),
	}
}
