// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AIGatewayRouteExpansion interface{}

type AIServiceBackendExpansion interface{}

type BackendSecurityPolicyExpansion interface{}

type MCPRouteExpansion interface{}
