// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAigatewayV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAigatewayV1alpha1) AIGatewayRoutes(namespace string) v1alpha1.AIGatewayRouteInterface {
	return newFakeAIGatewayRoutes(c, namespace)
}

func (c *FakeAigatewayV1alpha1) AIServiceBackends(namespace string) v1alpha1.AIServiceBackendInterface {
	return newFakeAIServiceBackends(c, namespace)
}

func (c *FakeAigatewayV1alpha1) BackendSecurityPolicies(namespace string) v1alpha1.BackendSecurityPolicyInterface {
	return newFakeBackendSecurityPolicies(c, namespace)
}

func (c *FakeAigatewayV1alpha1) MCPRoutes(namespace string) v1alpha1.MCPRouteInterface {
	return newFakeMCPRoutes(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAigatewayV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
