// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBackendSecurityPolicies implements BackendSecurityPolicyInterface
type fakeBackendSecurityPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.BackendSecurityPolicy, *v1alpha1.BackendSecurityPolicyList]
	Fake *FakeAigatewayV1alpha1
}

func newFakeBackendSecurityPolicies(fake *FakeAigatewayV1alpha1, namespace string) apiv1alpha1.BackendSecurityPolicyInterface {
	return &fakeBackendSecurityPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.BackendSecurityPolicy, *v1alpha1.BackendSecurityPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("backendsecuritypolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("BackendSecurityPolicy"),
			func() *v1alpha1.BackendSecurityPolicy { return &v1alpha1.BackendSecurityPolicy{} },
			func() *v1alpha1.BackendSecurityPolicyList { return &v1alpha1.BackendSecurityPolicyList{} },
			func(dst, src *v1alpha1.BackendSecurityPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BackendSecurityPolicyList) []*v1alpha1.BackendSecurityPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.BackendSecurityPolicyList, items []*v1alpha1.BackendSecurityPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
