// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAIGatewayRoutes implements AIGatewayRouteInterface
type fakeAIGatewayRoutes struct {
	*gentype.FakeClientWithList[*v1alpha1.AIGatewayRoute, *v1alpha1.AIGatewayRouteList]
	Fake *FakeAigatewayV1alpha1
}

func newFakeAIGatewayRoutes(fake *FakeAigatewayV1alpha1, namespace string) apiv1alpha1.AIGatewayRouteInterface {
	return &fakeAIGatewayRoutes{
		gentype.NewFakeClientWithList[*v1alpha1.AIGatewayRoute, *v1alpha1.AIGatewayRouteList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("aigatewayroutes"),
			v1alpha1.SchemeGroupVersion.WithKind("AIGatewayRoute"),
			func() *v1alpha1.AIGatewayRoute { return &v1alpha1.AIGatewayRoute{} },
			func() *v1alpha1.AIGatewayRouteList { return &v1alpha1.AIGatewayRouteList{} },
			func(dst, src *v1alpha1.AIGatewayRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AIGatewayRouteList) []*v1alpha1.AIGatewayRoute {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.AIGatewayRouteList, items []*v1alpha1.AIGatewayRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
