# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic-azure
  namespace: default
spec:
  parentRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: gpt-4.5-preview
      backendRefs:
        - name: envoy-ai-gateway-basic-azure
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-basic-azure
  namespace: default
spec:
  schema:
    name: AzureOpenAI
    version: 2025-01-01-preview
    ## OR using OpenAI compatible API
    # name: OpenAI
    # version: openai/v1
  backendRef:
    name: envoy-ai-gateway-basic-azure
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: envoy-ai-gateway-basic-azure-credentials
  namespace: default
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: envoy-ai-gateway-basic-azure
  type: AzureCredentials
  azureCredentials:
    clientID: AZURE_CLIENT_ID # Replace with your Azure Client ID.
    tenantID: AZURE_TENANT_ID # Replace with your Azure Tenant ID.
    clientSecretRef:
      name: envoy-ai-gateway-basic-azure-client-secret
      namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-basic-azure
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: dummy-azure-resource.openai.azure.com # Replace "dummy-azure-resource" with your Azure OpenAI resource e.g. <azure_resource_name>.openai.azure.com
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: envoy-ai-gateway-basic-azure-tls
  namespace: default
spec:
  targetRefs:
    - group: "gateway.envoyproxy.io"
      kind: Backend
      name: envoy-ai-gateway-basic-azure
  validation:
    wellKnownCACertificates: "System"
    hostname: dummy-azure-resource.openai.azure.com # Replace "dummy-azure-resource" with your Azure OpenAI resource e.g. <azure_resource_name>.openai.azure.com
---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-basic-azure-client-secret
  namespace: default
type: Opaque
stringData:
  client-secret: AZURE_CLIENT_SECRET # Replace with your Azure client secret for authentication.
